version: '3'
services:
  mysql:
    image: mysql:5.6.36
    env_file: .env
    restart: always
    volumes:
      - 'mysql-data:/var/lib/mysql'
      - './database:/tmp/db'
      - './mysqld_charset.cnf:/etc/mysql/conf.d/mysqld_charset.cnf'
    command: mysqld --init-file="/tmp/db/db_startup.sql" --max-connections=500
  mongodb:
    env_file:
      - .env
    image: tutum/mongodb:3.2
    volumes:
      - 'mongo-data:/data/db'
  remar:

      image: loaufscar/projeto-remar
      env_file:
        - .env
      restart: always
      host.docker.internal:
        - "host.docker.internal:host-gateway"
      ports:
        - '80:8080'
        - '8009:8009'
      volumes:
          - './conf/server.xml:/usr/local/tomcat/conf/server.xml'
          - '~/volume_docker_remar:/usr/local/tomcat/webapps'
          - '~/electron_docker:/root/.electron'
      links:
        - mongodb
        - mysql
      tty: true
volumes:
  mongo-data:
    driver: convoy
  mysql-data:
    driver: convoy
  remar-data:
    driver: convoy
