CREATE DATABASE IF NOT EXISTS remar;
CREATE DATABASE IF NOT EXISTS santograu;
CREATE DATABASE IF NOT EXISTS forca;
CREATE DATABASE IF NOT EXISTS escolamagica;
CREATE DATABASE IF NOT EXISTS mahjong;
CREATE DATABASE IF NOT EXISTS respondasepuder;

GRANT ALL PRIVILEGES
ON database.*
TO 'root'@'172.18.%'
IDENTIFIED BY 'root';