CREATE DATABASE IF NOT EXISTS remar;
CREATE DATABASE IF NOT EXISTS santograu;
CREATE DATABASE IF NOT EXISTS forca;
CREATE DATABASE IF NOT EXISTS escolamagica;
CREATE DATABASE IF NOT EXISTS mahjong;
CREATE DATABASE IF NOT EXISTS respondasepuder;