recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LdA8QkTAAAAANzRpkGUT__a9B2zHlU5Mnl6EDoJ"
	privateKey = "6LdA8QkTAAAAACHA9KoBPT1BXXBrJpQNJfCGTm9x"

	// Include the noscript tags in the generated captcha
	includeNoScript = true

    // Include the required script tag with the generated captcha
    includeScript = false
}

mailhide {
    // Generated by the Mailhide service
    publicKey = "6LdA8QkTAAAAANzRpkGUT__a9B2zHlU5Mnl6EDoJ"
    privateKey = "6LdA8QkTAAAAACHA9KoBPT1BXXBrJpQNJfCGTm9x"
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true
    }
  }
}